import Head from "next/head";
import classes from "src/styles/Home.module.css";
import Header from "src/components/Header";
import { client } from "/src/lib/client";
import Link from "next/link";

const Home = (props) => {
  console.log(props.contents);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={classes.wrapper}>
        <p>{`記事の総数: ${props.totalCount}件`}</p>
        <ul>
          {props.contents.map((content) => {
            return (
              <li key={content.id} className={classes.linkWrapper}>
                <Link href={`/blog/${content.id}`}>
                  <a className={classes.linkArticle}>
                    <img
                      src={content.image.url}
                      alt="画像"
                      className={classes.linkImage}
                    />
                    {content.title}
                  </a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
};

export const getStaticProps = async (ctx) => {
  const data = await client.getList({
    endpoint: "blog",
  });
  return {
    props: data,
  };
};

export default Home;
