import Head from "next/head";
import Footer from "src/components/footer/Footer";
import Introduction from "src/components/introduction";
import Links from "src/components/main";

const Home = (props) => {
  console.log(props.contents);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Links />
      <Introduction />
      <Footer />
    </div>
  );
};

export default Home;
